on:
  push:
    tags:
      - "v*.*.*"

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Zip artifact
        run: zip EFI.zip ./* -r
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: ./EFI.zip
          name: ThinkpadX390-OpenCore-EFI